name: eztimesheet
description: A simple timesheet management app for small business owners in Vietnam.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  sqflite: ^2.3.0
  sqflite_migration: ^2.0.0
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  battery_plus: ^5.0.2
  intl: ^0.18.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
